"""add_product_picture

Revision ID: 14baa8c4f320
Revises: 2624d7410577
Create Date: 2025-01-04 02:48:11.241471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14baa8c4f320'
down_revision: Union[str, None] = '2624d7410577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'picture')
    # ### end Alembic commands ###
